server.port=8088


# H2 Database setup

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA Config
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update


# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.defer-datasource-initialization=true


# ------------------------------
# Logging Configuration
# ------------------------------
logging.level.root=INFO
logging.level.demo_H2_jpa.UserManagentApi=DEBUG
logging.pattern.console= %logger{36} - %msg%n
